version: 2.0.{build}
clone_depth: 3
branches:
  only:
    - master
skip_tags: true
skip_commits:
  files:
    - docs/*
    - .travis.yml
    - README.md
    - TODO.md
    - coveralls.json
    - mkdocs.yml
    - requirements.txt
environment:
  MIX_ENV: test
cache:
  - _build
  - deps
init:
  - pwsh: . '.\bin\appveyor\init.ps1'
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix eqc.install --mini
build_script:
  - mix compile
test_script:
  - mix test --exclude=integration
  - mix test --only=win32:true
notifications:
  - provider: Email
    to:
      - paulschoenfelder@gmail.com
    on_build_status_changed: true
