version: 2.0.{build}
clone_depth: 3
image: Visual Studio 2017
branches:
  only:
    - master
skip_tags: true
skip_commits:
  files:
    - docs/*
    - .travis.yml
    - README.md
    - TODO.md
    - coveralls.json
    - mkdocs.yml
    - requirements.txt
environment:
  MIX_ENV: test
cache:
  - _build
  - deps
init:
  - choco install erlang
  - choco install elixir
  - SET PATH=C:\ProgramData\chocolatey\lib\Elixir\bin;C:\ProgramData\chocolatey\bin;%PATH%
  - refreshenv
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix eqc.install --mini
  - . .\bin\appveyor\start-epmd.ps1
build_script:
  - mix compile
test_script:
  - mix test --exclude=integration
  - mix test --only=win32:true
notifications:
  - provider: Email
    to:
      - paulschoenfelder@gmail.com
    on_build_status_changed: true
